package com.mckuai.imc.Utils.MCDao;

import android.database.sqlite.SQLiteDatabase;

import com.mckuai.imc.Bean.Forum;
import com.mckuai.imc.Bean.Type;
import com.mckuai.imc.Bean.User;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig forumDaoConfig;
    private final DaoConfig typeDaoConfig;

    private final UserDao userDao;
    private final ForumDao forumDao;
    private final TypeDao typeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        forumDaoConfig = daoConfigMap.get(ForumDao.class).clone();
        forumDaoConfig.initIdentityScope(type);

        typeDaoConfig = daoConfigMap.get(TypeDao.class).clone();
        typeDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        forumDao = new ForumDao(forumDaoConfig, this);
        typeDao = new TypeDao(typeDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Forum.class, forumDao);
        registerDao(Type.class, typeDao);
    }

    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        forumDaoConfig.getIdentityScope().clear();
        typeDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ForumDao getForumDao() {
        return forumDao;
    }

    public TypeDao getTypeDao() {
        return typeDao;
    }

}
