package com.mckuai.imc.Bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "Type".
 */
public class Type {

    private Long id;
    private Integer subId;
    /**
     * Not-null value.
     */
    private String name;

    public Type() {
    }

    public Type(Long id) {
        this.id = id;
    }

    public Type(Long id, Integer subId, String name) {
        this.id = id;
        this.subId = subId;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSubId() {
        return subId;
    }

    public void setSubId(Integer subId) {
        this.subId = subId;
    }

    /**
     * Not-null value.
     */
    public String getName() {
        return name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setName(String name) {
        this.name = name;
    }

    public PostType toPostType() {
        return new PostType(id.intValue(), subId, name);
    }

}
